### PR TITLE
perf: use win32 API instead of WMI to query process information

### PR DESCRIPTION
**Pull request by chengyuhui**
Update the Windows implementation to use native Windows APIs instead of WMI, which does not consume much CPU (barely noticeable when polling with an interval of 1 second).

This should also remove the dependency on `wmi` package, but I am having difficulty using Poetry, so that change is not made.

### CODE REVIEW

**Comment by ErikBjare** [comment]
This is awesome. Great work, thanks!

**Comment by ErikBjare** [comment]
@chengyuhui This created a regression for applications run as administrator, which you can read about in https://github.com/ActivityWatch/activitywatch/issues/873

Are you interested in working on a fix? Namely to use the newer method, but in the cases that it fails, fallback to using wmi.

I've asked @BelKed about it [here](https://github.com/ActivityWatch/activitywatch/issues/873#issuecomment-1785894619), thought I'd ask you too :)

**Comment by chengyuhui** [comment]
I no longer use AW on my Windows system since I have migrated my main desktop to Arch. You guys can go ahead and fix this :)

**Comment by ErikBjare** [comment]
Congratulations on Arch-maxing! :star_struck: 

I guess I'll make a PR myself and find someone to test it later :)

**Pull request merged**
