### PR TITLE
feat: added back wmi method on Windows as fallback for admin processes

### LINKED ISSUE #94: [Windows] Apps run in Administrator not got recorded
I saw some vacancy on the timeline. 
image

After some tests I realized they are apps run as administrator (e.g. `Windows Terminal (Admin)`, `Process Hacker (Administrator)` ), which don't have any logs in the Raw Data.

I tried `12.2` and `12.3b15`, both the same.

I tried to set `Run As Administrator` in the properties of `aw-watcher-window.exe`, but it just fail to start by `aw-qt`

### PR DESCRIPTION
**Pull request by ErikBjare**
I haven't tested this or anything, flying blind on a non-Windows machine, but shouldn't be much more than this.

Addresses regression caused by https://github.com/ActivityWatch/aw-watcher-window/pull/83

Fixes #94 
Fixes https://github.com/ActivityWatch/activitywatch/issues/873
Fixes https://github.com/ActivityWatch/activitywatch/issues/1004

### CODE REVIEW

**Comment by ErikBjare** [comment]
As I wrote in #1004:

> Might be bold and merge this without testing it myself. Goal is to get a new beta release out that fixes this ASAP (along with another window watcher fix for macOS).

**Comment by vasiliy-pdk** [comment]
Thanks for the fix! 👍  I am eager to test it to fix Helldivers 2 tracking information missing https://github.com/ActivityWatch/activitywatch/issues/1029 

Not sure how to test it though. I found this release https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b16 that includes the commits from this branch but there's a warning saying that the release is broken on several platforms. I [checked the freshest beta release ](https://github.com/ActivityWatch/activitywatch/compare/v0.12.2...v0.12.3b19) and found no commits from this branch. 

Was it reverted or there's another fix elsewhere?

**Comment by ErikBjare** [comment]
@vasiliy-pdk Try a newer beta than v0.12.3b16.

The commit won't show up in the commit history you linked, since the change happened in a submodule. But it is included in the [release notes for v0.12.3b16](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b16), which are generated including submodules.

**Comment by vasiliy-pdk** [comment]
Thanks! Installed the most recent beta release and can track Helldivers 2 now.

**Pull request merged**
