### PR TITLE
Added command line option to exclude window title from events

### PR DESCRIPTION
**Pull request by ErikBjare**

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
How does this work with the webapp visualization?

Does it totally break or does it simply just not show any titles?

**Comment by ErikBjare** [comment]
@johan-bjareholt I have no clue, I'll investigate before merging.

**Comment by johan-bjareholt** [comment]
Or you could just set the title as "Unknown", "Hidden" or something similar

**Comment by ErikBjare** [comment]
@johan-bjareholt I did as you said and set the title as "title:excluded".

**Comment by ErikBjare** [comment]
Merging this, should be problem-free.

**Pull request merged**
